- name: Hôte ARM — socle durci et pile de jeu
  hosts: arm
  become: true
  pre_tasks:
    - name: Collections requises
      ansible.builtin.import_tasks: collections.yml
  roles:
    - base
    - minecraft

- name: Hôte edge — socle durci
  hosts: edge
  become: true
  pre_tasks:
    - name: Collections requises
      ansible.builtin.import_tasks: collections.yml
  roles:
    - base
